# Generated by Django 6.0.2 on 2026-03-07 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_full_name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('official_contact', models.CharField(max_length=15)),
                ('ward_name', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('aadhaar_image', models.ImageField(upload_to='ward/aadhaar/')),
                ('selfie_image', models.ImageField(upload_to='ward/selfie/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='ward/supporting/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('panchayath', models.ForeignKey(limit_choices_to={'role': 'PANCHAYATH'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_wards', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'WARD'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
