# Generated by Django 6.0.2 on 2026-03-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
