# Generated by Django 6.0.2 on 2026-04-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_resolutionmedia'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/escalation_media/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_media', to='complaints.complaint')),
            ],
        ),
    ]
