# Generated by Django 6.0.2 on 2026-05-20 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0002_escalationmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wardverification',
            name='supporting_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
