# Generated by Django 6.0.2 on 2026-05-21 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0003_alter_escalationmedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='aadhaar_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wardverification',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
