# Generated by Django 6.0.2 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_locationrequest'),
        ('ward', '0004_alter_wardverification_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardverification',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_verifications', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='wardverification',
            name='panchayath_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_verifications', to='accounts.panchayath'),
        ),
        migrations.AddField(
            model_name='wardverification',
            name='ward_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ward_verifications', to='accounts.ward'),
        ),
    ]
