# Generated by Django 6.0.2 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0005_wardverification_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PANCHAYATH', 'Waiting for Panchayath Officer'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
    ]
