# Generated by Django 6.0.2 on 2026-07-03 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0006_alter_wardverification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='panchayath',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PANCHAYATH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
