# Generated by Django 6.0.2 on 2026-07-30 20:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0008_wardofficerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='aadhaar_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wardverification',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
