# Generated by Django 6.0.2 on 2026-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0009_alter_wardverification_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PANCHAYATH', 'Waiting for Panchayath Officer'), ('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=50),
        ),
    ]
