# Generated by Django 6.0.2 on 2026-07-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0010_alter_wardverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardverification',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wardverification',
            name='officer_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
