# Generated by Django 6.0.2 on 2026-06-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Panchayath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayaths', to='accounts.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.PositiveIntegerField()),
                ('ward_name', models.CharField(blank=True, max_length=150, null=True)),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='accounts.panchayath')),
            ],
            options={
                'ordering': ['ward_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='panchayath',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_panchayath_per_district'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('panchayath', 'ward_number'), name='unique_ward_per_panchayath'),
        ),
    ]
