# Generated by Django 6.0.2 on 2026-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_district_code_panchayath_code_ward_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayath',
            name='html_page',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
