# Generated by Django 6.0.2 on 2026-07-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_panchayath_html_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('DISTRICT', 'District'), ('PANCHAYATH', 'Panchayath'), ('WARD', 'Ward')], max_length=20)),
                ('district_name', models.CharField(blank=True, max_length=150)),
                ('panchayath_name', models.CharField(blank=True, max_length=150)),
                ('ward_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
