# Generated by Django 6.0.2 on 2026-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_password_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
