# Generated by Django 6.0.2 on 2026-07-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_set_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_users', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='panchayath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_users', to='accounts.panchayath'),
        ),
    ]
