# Generated by Django 6.0.2 on 2026-07-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_district_user_panchayath'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_users', to='accounts.ward'),
        ),
    ]
