# Generated by Django 6.0.2 on 2026-07-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='set_password_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
