# Generated by Django 6.0.2 on 2026-04-22 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0010_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification', max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('COMPLAINT_STATUS', 'Complaint Status'), ('UPVOTE', 'Upvote'), ('COMMENT', 'Comment'), ('REPLY', 'Reply'), ('CHAT', 'Chat Message'), ('CITIZEN_VERIFICATION', 'Citizen Verification'), ('WARD_VERIFICATION', 'Ward Verification'), ('PANCHAYATH_VERIFICATION', 'Panchayath Verification'), ('ESCALATION', 'Escalation'), ('REASSIGN', 'Reassign'), ('RESOLUTION', 'Resolution'), ('ALERT', 'System Alert')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
