# Generated by Django 6.0.2 on 2026-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_COMPLAINT', 'New Complaint'), ('COMPLAINT_STATUS', 'Complaint Status'), ('UPVOTE', 'Upvote'), ('COMMENT', 'Comment'), ('REPLY', 'Reply'), ('CHAT', 'Chat Message'), ('CITIZEN_VERIFICATION', 'Citizen Verification'), ('WARD_VERIFICATION', 'Ward Verification'), ('PANCHAYATH_VERIFICATION', 'Panchayath Verification'), ('ESCALATION', 'Escalation'), ('REASSIGN', 'Reassign'), ('RESOLUTION', 'Resolution'), ('ALERT', 'System Alert')], max_length=30),
        ),
    ]
