# Generated by Django 6.0.2 on 2026-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
