# Generated by Django 6.0.2 on 2026-02-21 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhaar_image', models.ImageField(upload_to='block_verification/aadhaar_id/')),
                ('appointment_letter', models.FileField(upload_to='block_verification/government_ids/')),
                ('live_selfie', models.ImageField(upload_to='block_verification/selfies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
