# Generated by Django 6.0.2 on 2026-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockverification',
            name='appointment_letter',
            field=models.FileField(upload_to='block_verification/appointment_letters/'),
        ),
    ]
