# Generated by Django 6.0.2 on 2026-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_alter_blockverification_appointment_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockverification',
            name='block_name',
            field=models.CharField(default='Default Block', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockverification',
            name='district',
            field=models.CharField(default='Default District', max_length=20),
            preserve_default=False,
        ),
    ]
