# Generated by Django 6.0.2 on 2026-05-12 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_deleted_at_message_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat'], name='chat_messag_chat_id_7e5d57_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='chat_messag_is_dele_543a03_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['file_type'], name='chat_messag_file_ty_bbaf8d_idx'),
        ),
    ]
