# Generated by Django 6.0.2 on 2026-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_message_chat_messag_is_read_872c73_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/'),
        ),
    ]
