# Generated by Django 6.0.2 on 2026-05-21 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
