# Generated by Django 6.0.2 on 2026-02-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayathVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhaar_image', models.ImageField(upload_to='panchayath_verification/aadhaar_images/')),
                ('appointment_letter', models.FileField(upload_to='panchayath_verification/appointment_letters/')),
                ('government_id', models.FileField(upload_to='panchayath_verification/government_ids/')),
                ('live_selfie', models.ImageField(upload_to='panchayath_verification/selfies/')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_panchayaths', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panchayath_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
