# Generated by Django 6.0.2 on 2026-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayathverification',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='panchayathverification',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
