# Generated by Django 6.0.2 on 2026-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayathverification',
            name='government_id',
        ),
    ]
