# Generated by Django 6.0.2 on 2026-05-21 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayathverification',
            name='aadhaar_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='panchayathverification',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
