# Generated by Django 6.0.2 on 2026-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0002_remove_panchayathverification_government_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panchayathverification',
            old_name='rejection_reason',
            new_name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='live_selfie',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='panchayathverification',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='district',
            field=models.CharField(default='no reason', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='panchayath_name',
            field=models.CharField(default='No reason', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='selfie_image',
            field=models.ImageField(default='0000000000', upload_to='panchayath/selfie/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='panchayathverification',
            name='aadhaar_image',
            field=models.ImageField(upload_to='panchayath/aadhaar/'),
        ),
    ]
