# Generated by Django 6.0.2 on 2026-07-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_locationrequest'),
        ('panchayath', '0002_alter_panchayathverification_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayathverification',
            name='district_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panchayath_verifications', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='panchayath_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='accounts.panchayath'),
        ),
    ]
