# Generated by Django 6.0.2 on 2026-02-28 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0003_rename_rejection_reason_panchayathverification_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayathverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
