# Generated by Django 6.0.2 on 2026-07-30 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0003_panchayathverification_district_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayathOfficerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_phone', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('replacement_reason', models.TextField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('office', models.ForeignKey(limit_choices_to={'role': 'PANCHAYATH'}, on_delete=django.db.models.deletion.CASCADE, related_name='panchayath_officer_history', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_panchayath_officers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-replaced_at'],
            },
        ),
    ]
