# Generated by Django 6.0.2 on 2026-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0004_panchayathverification_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayathverification',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panchayathverification',
            name='full_name',
            field=models.CharField(default='defaultname', max_length=50),
            preserve_default=False,
        ),
    ]
