# Generated by Django 6.0.2 on 2026-07-30 17:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0004_panchayathofficerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayathverification',
            name='aadhaar_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='panchayathverification',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
