# Generated by Django 6.0.2 on 2026-07-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayath', '0005_alter_panchayathverification_aadhaar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panchayathverification',
            name='status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
    ]
