# Generated by Django 6.0.2 on 2026-03-07 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ROAD', 'Road Issue'), ('WATER', 'Water Issue'), ('ELECTRICITY', 'Electricity'), ('WASTE', 'Waste Management'), ('OTHER', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('image_proof', models.ImageField(blank=True, null=True, upload_to='complaints/images/')),
                ('video_proof', models.FileField(blank=True, null=True, upload_to='complaints/videos/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('chat_closed', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(limit_choices_to={'role': 'CITIZEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_complaints', to=settings.AUTH_USER_MODEL)),
                ('panchayath', models.ForeignKey(blank=True, limit_choices_to={'role': 'PANCHAYATH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panchayath_complaints', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(limit_choices_to={'role': 'WARD'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(limit_choices_to={'role__in': ['WARD', 'PANCHAYATH']}, on_delete=django.db.models.deletion.CASCADE, related_name='authority_chats', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_chats', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.complaintchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='complaints/resolution_images/')),
                ('proof_video', models.FileField(blank=True, null=True, upload_to='complaints/resolution_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('COMMENT', 'Comment'), ('UPVOTE', 'Upvote'), ('RESOLUTION', 'Resolution'), ('CHAT', 'Chat Message'), ('ESCALATION', 'Escalation')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['ward'], name='complaints__ward_id_942263_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['panchayath'], name='complaints__panchay_ff2830_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintupvote',
            index=models.Index(fields=['complaint'], name='complaints__complai_2ca1e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complaintupvote',
            unique_together={('complaint', 'user')},
        ),
    ]
