# Generated by Django 6.0.2 on 2026-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_escalation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reassign_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
