# Generated by Django 6.0.2 on 2026-03-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complainthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resolution_description',
        ),
    ]
