# Generated by Django 6.0.2 on 2026-03-06 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintchat_complaintchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='complaints/resolution_images/')),
                ('proof_video', models.FileField(blank=True, null=True, upload_to='complaints/resolution_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='complaints.complaint')),
            ],
        ),
    ]
