# Generated by Django 6.0.2 on 2026-04-01 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_remove_complaint_resolution_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/media/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='complaints.complaint')),
            ],
        ),
    ]
