# Generated by Django 6.0.2 on 2026-03-06 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaintresolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('COMMENT', 'Comment'), ('UPVOTE', 'Upvote'), ('RESOLUTION', 'Resolution'), ('CHAT', 'Chat Message'), ('ESCALATION', 'Escalation')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complaintchat',
            name='authority',
            field=models.ForeignKey(limit_choices_to={'role__in': ['WARD', 'PANCHAYATH']}, on_delete=django.db.models.deletion.CASCADE, related_name='authority_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['ward'], name='complaints__ward_id_942263_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['panchayath'], name='complaints__panchay_ff2830_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintupvote',
            index=models.Index(fields=['complaint'], name='complaints__complai_2ca1e4_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
