# Generated by Django 6.0.2 on 2026-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_resolutionmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_reassigned',
            field=models.BooleanField(default=False),
        ),
    ]
