# Generated by Django 6.0.2 on 2026-04-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_is_reassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='complaints.complaintcomment'),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
