# Generated by Django 6.0.2 on 2026-04-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaintcomment_parent_complaintcomment_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
