# Generated by Django 6.0.2 on 2026-04-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintchatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='complaintchatmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ComplaintChat',
        ),
        migrations.DeleteModel(
            name='ComplaintChatMessage',
        ),
    ]
