# Generated by Django 6.0.2 on 2026-05-20 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_remove_complaintchatmessage_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='video_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaintmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaintresolution',
            name='proof_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resolutionmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
