# Generated by Django 6.0.2 on 2026-05-21 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_complaint_video_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaintresolution',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
