# Generated by Django 6.0.2 on 2026-07-05 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_locationrequest'),
        ('complaints', '0013_alter_complaint_image_proof_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_ward_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'WARD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='accounts.ward'),
        ),
    ]
