# Generated by Django 6.0.2 on 2026-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaintcomment_reply_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='panchayath_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
