# Generated by Django 6.0.2 on 2026-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='street_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='ward_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
