# Generated by Django 6.0.2 on 2026-05-21 06:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_citizenprofile_address_citizenprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citizenverification',
            name='aadhaar_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citizenverification',
            name='selfie_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
