# Generated by Django 6.0.2 on 2026-07-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_locationrequest'),
        ('citizen', '0003_alter_citizenprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenverification',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizen_verifications', to='accounts.ward'),
        ),
    ]
