# Generated by Django 6.0.2 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_alter_citizenverification_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenverification',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_WARD', 'Waiting for Ward Officer'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
