# Generated by Django 6.0.2 on 2026-07-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_locationrequest'),
        ('citizen', '0005_alter_citizenverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenverification',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citizen_verifications', to='accounts.ward'),
        ),
    ]
