export const CURRENT_USER = {
  id: "panchayath-001",
  name: "Panchayath Office",
  designation: "Secretary, Tirur Panchayath",
  role: "Panchayath",
};

export const CONTACTS = [
  {
    id: "ward-001",
    name: "Ward 1 – Tirur North",
    role: "Ward Member",
    designation: "Ward Member, Tirur North",
    isOnline: true,
    lastSeen: null,
    lastMessage: "The road repair work has been completed ✅",
    timestamp: "10:42 AM",
    unreadCount: 2,
  },
  {
    id: "ward-002",
    name: "Ward 2 – Tirur South",
    role: "Ward Member",
    designation: "Ward Member, Tirur South",
    isOnline: false,
    lastSeen: "2 hrs ago",
    lastMessage: "Please review the drainage report",
    timestamp: "9:15 AM",
    unreadCount: 0,
  },
  {
    id: "ward-003",
    name: "Ward 3 – Market Area",
    role: "Ward Member",
    designation: "Ward Member, Market Area",
    isOnline: true,
    lastSeen: null,
    lastMessage: "Sent you the inspection photos",
    timestamp: "Yesterday",
    unreadCount: 5,
  },
  {
    id: "ward-004",
    name: "Ward 4 – Eastside",
    role: "Ward Member",
    designation: "Ward Member, Eastside",
    isOnline: false,
    lastSeen: "1 day ago",
    lastMessage: "Meeting scheduled for Friday 3 PM",
    timestamp: "Yesterday",
    unreadCount: 0,
  },
  {
    id: "ward-005",
    name: "Ward 5 – River Bank",
    role: "Ward Member",
    designation: "Ward Member, River Bank",
    isOnline: true,
    lastSeen: null,
    lastMessage: "Flood alert issued for the zone",
    timestamp: "Mon",
    unreadCount: 1,
  },
  {
    id: "ward-006",
    name: "Ward 6 – Industrial",
    role: "Ward Member",
    designation: "Ward Member, Industrial",
    isOnline: false,
    lastSeen: "3 days ago",
    lastMessage: "Water supply issue resolved",
    timestamp: "Mon",
    unreadCount: 0,
  },
];

export const MESSAGES_BY_CONTACT = {
  "ward-001": [
    {
      id: "m1",
      senderId: "ward-001",
      senderName: "Ward 1",
      text: "Good morning, Secretary. We have received multiple complaints about the road near Main Junction.",
      timestamp: "9:00 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Good morning. When did these complaints come in? Please share the complaint reference numbers.",
      timestamp: "9:03 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-001",
      senderName: "Ward 1",
      text: "Complaints received on 12 May. Reference IDs: SPIMS-2024-441, SPIMS-2024-442, SPIMS-2024-445",
      timestamp: "9:05 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m4",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Noted. I'll escalate to the PWD department immediately. Please coordinate with the site engineer.",
      timestamp: "9:10 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m5",
      senderId: "ward-001",
      senderName: "Ward 1",
      file: {
        fileType: "pdf",
        name: "Road_Inspection_Report_May2024.pdf",
        size: "1.2 MB",
      },
      text: "Please find the inspection report attached.",
      timestamp: "9:18 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m6",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Thank you. Report received. Work order will be issued by EOD.",
      timestamp: "10:00 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m7",
      senderId: "ward-001",
      senderName: "Ward 1",
      text: "The road repair work has been completed ✅",
      timestamp: "10:42 AM",
      date: "Today",
      status: "delivered",
      replyTo: {
        senderName: "Panchayath",
        text: "Work order will be issued by EOD.",
      },
    },
  ],
  "ward-002": [
    {
      id: "m1",
      senderId: "ward-002",
      senderName: "Ward 2",
      text: "Namaskar. The drainage situation in Tirur South is getting critical.",
      timestamp: "8:30 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Understood. Has this been logged in SPIMS already?",
      timestamp: "8:45 AM",
      date: "Today",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-002",
      senderName: "Ward 2",
      text: "Yes, logged as SPIMS-2024-460. Please review the drainage report.",
      timestamp: "9:15 AM",
      date: "Today",
      status: "seen",
      file: {
        fileType: "pdf",
        name: "Drainage_Report_Ward2.pdf",
        size: "840 KB",
      },
    },
  ],
  "ward-003": [
    {
      id: "m1",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Ward 3 team, please share the status of the market area cleanliness drive.",
      timestamp: "11:00 AM",
      date: "Yesterday",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "ward-003",
      senderName: "Ward 3",
      text: "Drive completed successfully. Over 2 tonnes of waste collected.",
      timestamp: "11:30 AM",
      date: "Yesterday",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-003",
      senderName: "Ward 3",
      text: "Sent you the inspection photos",
      timestamp: "11:35 AM",
      date: "Yesterday",
      status: "seen",
      file: {
        fileType: "image",
        name: "Market_Cleanup.jpg",
        url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
        preview: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
      },
    },
  ],
  "ward-004": [
    {
      id: "m1",
      senderId: "ward-004",
      senderName: "Ward 4",
      text: "Good afternoon. Monthly review meeting is being planned.",
      timestamp: "2:00 PM",
      date: "Yesterday",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Please suggest a time slot.",
      timestamp: "2:15 PM",
      date: "Yesterday",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-004",
      senderName: "Ward 4",
      text: "Meeting scheduled for Friday 3 PM",
      timestamp: "3:00 PM",
      date: "Yesterday",
      status: "seen",
      isForwarded: false,
    },
  ],
  "ward-005": [
    {
      id: "m1",
      senderId: "ward-005",
      senderName: "Ward 5",
      text: "URGENT: River bank area is showing signs of flooding. Water level has risen by 30 cm in the last 2 hours.",
      timestamp: "7:00 AM",
      date: "Monday",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "Alert received. Evacuating residents immediately. KSEB and Revenue officials informed.",
      timestamp: "7:10 AM",
      date: "Monday",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-005",
      senderName: "Ward 5",
      text: "Flood alert issued for the zone",
      timestamp: "7:30 AM",
      date: "Monday",
      status: "delivered",
    },
  ],
  "ward-006": [
    {
      id: "m1",
      senderId: "ward-006",
      senderName: "Ward 6",
      text: "Water supply to the industrial zone was disrupted since morning.",
      timestamp: "10:00 AM",
      date: "Monday",
      status: "seen",
    },
    {
      id: "m2",
      senderId: "panchayath-001",
      senderName: "Panchayath",
      text: "KWA has been notified. Tanker arranged as interim solution.",
      timestamp: "10:30 AM",
      date: "Monday",
      status: "seen",
    },
    {
      id: "m3",
      senderId: "ward-006",
      senderName: "Ward 6",
      text: "Water supply issue resolved",
      timestamp: "2:00 PM",
      date: "Monday",
      status: "seen",
    },
  ],
};